name: Windows 2022 RDP

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # روزانه اجرا شود (اختیاری)

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and extract Ngrok
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok" -Force
        Remove-Item -Path "ngrok.zip" -Force

    - name: Setup Ngrok Auth
      shell: powershell
      run: .\ngrok\ngrok.exe authtoken "$Env:NGROK_AUTH_TOKEN"
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP and configure administrator account
      shell: powershell
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        # Enable Administrator account and set password
        $adminPassword = "qaz123!@#"
        $securePassword = ConvertTo-SecureString $adminPassword -AsPlainText -Force
        
        # Enable administrator account
        Enable-LocalUser -Name "Administrator"
        Set-LocalUser -Name "Administrator" -Password $securePassword
        
        # Add administrator to remote desktop users group
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Administrator"
        
        Write-Host "=============================================="
        Write-Host "Administrator account enabled successfully!"
        Write-Host "Username: Administrator"
        Write-Host "Password: qaz123!@#"
        Write-Host "=============================================="

    - name: Create connection info file
      shell: powershell
      run: |
        # Create a connection info file
        @"
        @echo off
        echo ==============================================
        echo    Windows 2022 RDP Connection Information
        echo ==============================================
        echo.
        echo Username: Administrator
        echo Password: qaz123!@#
        echo.
        echo Waiting for Ngrok tunnel to be established...
        echo ==============================================
        pause
        "@ > connection-info.bat

    - name: Start Ngrok Tunnel
      shell: powershell
      run: |
        # Start Ngrok in background
        $ngrokProcess = Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -PassThru
        
        # Wait for tunnel to establish
        Start-Sleep -Seconds 15
        
        # Get tunnel information
        try {
            $tunnels = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -ErrorAction Stop
            if ($tunnels.tunnels.Count -gt 0) {
                $public_url = $tunnels.tunnels[0].public_url
                $public_url = $public_url -replace "tcp://", ""
                $hostname, $port = $public_url -split ":"
                
                Write-Host "=============================================="
                Write-Host "RDP Connection Information:"
                Write-Host "Host: $hostname"
                Write-Host "Port: $port"
                Write-Host "Username: Administrator"
                Write-Host "Password: qaz123!@#"
                Write-Host "=============================================="
                
                # Save connection info to a file
                @"
==============================================
Windows 2022 RDP Connection Information
==============================================
Host: $hostname
Port: $port
Username: Administrator
Password: qaz123!@#
==============================================
"@ > rdp-connection-info.txt
                
                # Display connection info
                Get-Content rdp-connection-info.txt
            }
        } catch {
            Write-Host "Failed to retrieve Ngrok tunnel information: $($_.Exception.Message)"
            Write-Host "Please check https://dashboard.ngrok.com/endpoints/status for tunnel status"
        }
        
        # Keep the runner active
        Write-Host "RDP session is now active. Press Ctrl+C to stop."
        while ($true) {
            Write-Host "RDP session active - $(Get-Date)"
            Start-Sleep -Seconds 300
        }
