name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    # Checkout کل ریپو (فایل‌های ngrok.zip، start-2022.bat، ... باید داخل ریپو باشند)
    - name: Checkout repository
      uses: actions/checkout@v3

    # بررسی وجود فایل‌ها
    - name: List files
      run: dir

    # اکسترکت ngrok
    - name: Extract ngrok
      run: Expand-Archive .\ngrok-v3-stable-windows-amd64.zip -DestinationPath .\ngrok

    # تنظیم Ngrok
    - name: Connect to Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # فعال کردن RDP و کپی فایل‌ها
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy .\wallpaper.png C:\Users\Public\Desktop\wallpaper.png
        copy .\wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat
        copy .\start-2022.bat .\start-2022.bat
        copy .\loop.bat .\loop.bat

    # باز کردن تونل Ngrok
    - name: Open Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    # اجرا کردن RDP
    - name: Connect to RDP
      run: cmd /c start-2022.bat

    # حلقه برای ادامه کار
    - name: Loop
      run: cmd /c loop.bat
